### ISSUE TITLE
[FEATURE] Expandable Instructions Textarea for Enhanced Editing Experience

### ISSUE THREAD

**Issue by enricobellato** [logicleai/logicle#18]
### 🔖 Describe the Feature

The proposed feature involves adding an expand button on the instructions textarea. This button, when clicked, would open a much larger (almost full screen) text area where the user can edit everything in a more spacious environment. This enhancement aims to provide a more user-friendly interface for editing the main instruction prompts.

### 🎤 Justification for the Feature

This feature addresses a significant user experience (UX) issue where users currently face difficulties editing the main instruction prompts due to the limited space provided by the existing textarea. By introducing a larger, almost full-screen editing area, users will have a more comfortable and efficient editing experience, ultimately improving the overall usability of the platform.

### ✌️ Proposed Solution

Implement an expand button on the current instructions textarea. Upon clicking this button, a new, larger text area should be displayed, occupying almost the full screen. This expanded view will allow users to edit text more comfortably, addressing the current UX limitations. The implementation should ensure that all existing functionalities, such as text formatting and input validation, remain intact in the expanded view.

### 👀 Duplicate Check

- [x] I have searched and found no similar feature request

### 🏢 Code of Conduct Acknowledgement

- [X] I have read the [Contributing Guidelines](https://github.com/logicleai/logicle/blob/main/CONTRIBUTING.md)

**Comment by protoism** [comment]
You are talking about assistant instructions i.e. system prompt?

**Comment by enricobellato** [comment]
Yes, exactly that – it's about making the assistant instructions in the system prompt easier to work with. Thinking of starting with something like the ChatGPT GPT Builder's expandable text area. Plus, we can also tweak the text area to be taller even when it's not fully expanded.

<img width="1512" alt="Screenshot 2024-03-17 alle 15 03 02" src="https://github.com/logicleai/logicle/assets/58302982/3c5cfb93-2395-40d3-9c5b-4f0ba2afba40">
<img width="1512" alt="Screenshot 2024-03-17 alle 15 03 09" src="https://github.com/logicleai/logicle/assets/58302982/f93ea8ac-66c2-4642-bd4e-20546a5c7c1c">

**Comment by enricobellato** [comment]
Following our private discussion with @protoism, we have decided to transition to a tabbed interface for the design. This layout will maintain its bifurcated structure, dedicating the right section to live testing of the created model, while the left section will house the configuration options.

Within the left section, users will navigate between two or three distinct categories via tabs:
- **First Tab – General Information**: This tab is dedicated to setting up the basic details of the assistant, such as its name, logo, and description. It's designed to allow users to personalize their assistant at a glance.
- **Second Tab – Prompt and Context**: The primary focus here is on providing a maximized and horizontally expandable prompt text area. This enhancement aims to significantly improve the user experience by facilitating easier and more comfortable prompt creation. Below the prompt area, users can attach relevant files and activate custom tools, further enriching the assistant's context.
- **Third Tab – Model Settings**: In this tab, users can select the backend and model of their choice. Additionally, it offers access to "advanced settings" where parameters like temperature and Token Limit can be adjusted to fine-tune the model's behavior.

The rationale behind adopting a tabbed design is to alleviate the clutter caused by the current linear arrangement of options, which is expected to become more congested as new features are introduced. By allocating more screen space to each critical aspect of assistant creation through tabs, we aim to enhance the overall user experience and streamline the configuration process.

**Comment by protoism** [comment]
PR #64 does not exactly what requested in this issue.
I dedicated an entire tab to the prompt, and left the rest in "other".
A better split, in my opinion, is:
1) General
2) System prompt
3) Knowledge
I say "better" not because it's more consistent / clever, but because I have the sensation that the typical process of creation of an assistant focuses on one area at a time
Does it make sense?

**Comment by protoism** [comment]
Closing issue as this solution has been accepted:

1. General
2. System prompt
3. Tools
