### ISSUE TITLE
[BUG] Textarea Width Too Small When Editing Messages in Chat

### ISSUE THREAD

**Issue by enricobellato** [logicleai/logicle#19]
### 📜 Issue Description

When attempting to edit an existing message within a chat interface, the textarea designated for editing displays with a width significantly narrower than the width of the messages themselves. This discrepancy poses a considerable inconvenience, particularly when editing longer messages, as it compels the user to engage in excessive vertical scrolling to view and edit the entirety of the message.

### 👟 Steps to Reproduce

1. Go to an existing chat conversation.
2. Click on 'Edit' for a message you've previously sent.
3. Notice that the text area provided for editing the message is significantly narrower compared to the width of the original message. This discrepancy causes an unnecessary increase in vertical scrolling.

### 👎 Current Behavior with Screenshots

Currently, when editing a long message in the chat, the editing textarea appears significantly narrower than the displayed message width. This forces users into an inconvenient vertical scrolling to edit the message fully.
![Screenshot 2024-03-14 alle 12 11 56](https://github.com/logicleai/logicle/assets/58302982/8b1af0d5-dd8f-44bc-b7b5-f83c392d9d94)

### 👍 Expected Behavior

The expected behavior is for the textarea used for editing messages in the chat to match or closely approximate the width of the messages themselves. This would eliminate the need for vertical scrolling, thereby facilitating a more user-friendly editing experience, especially for longer messages.

### 🏢 Code of Conduct Acknowledgement

- [X] I have read the [Contributing Guidelines](https://github.com/logicleai/logicle/blob/main/CONTRIBUTING.md)

**Comment by protoism** [comment]
Can you paste here the message you sent?
I can't replicate. I wonder if it is related to something weird in the message
