### ISSUE TITLE
[BUG] Generic error

### ISSUE THREAD

**Issue by mgaionWalit** [logicleai/logicle#24]
### 📜 Issue Description

case 1: while trying configure a new assistant without a backend configured, i get a generic (not describing) error.
case 2: while removing backends with assistant configured i get another not detailed error

Docker side i can see this error
_Unexpected exception: Error: Constraint not respected (foreign key)_

### 👟 Steps to Reproduce

case 1: try to add a new assistant without any backend configured
case 2: try to delete a backend (openAI) already configured with an assistant connected

### 👎 Current Behavior with Screenshots

![image](https://github.com/logicleai/logicle/assets/127841245/bfc3aecf-8fd9-4c03-b7ce-693cc2d235ab)

### 👍 Expected Behavior

on case 1: i expect an error that issue me to configure at least 1 backend
on case 2: i suspect the error is caused by the presence of an assistant connected to this backend, but the error must tell me something to understand it.

### 📃 Additional Context

Sorry if i put 2 behaviours on the same issue, but in my opinion those are "logical" connected.

Thanks for your time

### 🏢 Code of Conduct Acknowledgement

- [X] I have read the [Contributing Guidelines](https://github.com/logicleai/logicle/blob/main/CONTRIBUTING.md)

**Comment by protoism** [comment]
PR #30 and #31 should fix both issues.
As I discovered that it was perfectly fine to delete a Backend used by an Assistant, I suspect that your error message was related to another kind of "usage" (foreign key).
If the assistant had just been created, well... there's more investigation to do.
Can you confirm that the issue is fixed?
