### ISSUE TITLE
[BUG] Assistant Knowledge configuration (but not used)

### ISSUE THREAD

**Issue by mgaionWalit** [logicleai/logicle#25]
### 📜 Issue Description

I configured a new assistant and i tried add a file as knowledge, but the informations inside arent used

### 👟 Steps to Reproduce

1-configure a new assistant
2-add a file with the knoledge + icon
3-ask a simple information in the file to the assistant

### 👎 Current Behavior with Screenshots

![image](https://github.com/logicleai/logicle/assets/127841245/fa4feb85-05fe-465c-9236-2d35ebf8e963)

### 👍 Expected Behavior

in case the knowledge use isnt yet implemented, remove the misleading option.

### 🏢 Code of Conduct Acknowledgement

- [X] I have read the [Contributing Guidelines](https://github.com/logicleai/logicle/blob/main/CONTRIBUTING.md)

**Comment by protoism** [comment]
Those controls should be hidden!
Knowledge and tools are not ready for primetime :)
