### ISSUE TITLE
[BUG] typo error on edit backends

### ISSUE THREAD

**Issue by mgaionWalit** [logicleai/logicle#27]
### 📜 Issue Description

once editing a backend, the button to save is labeled "create backend"

### 👟 Steps to Reproduce

1- open administrator setting
2- open backends section
3- click on any backend name to edit it

### 👎 Current Behavior with Screenshots

![image](https://github.com/logicleai/logicle/assets/127841245/1b89a7b9-4f62-46e5-90da-2a97dfa272ff)

### 👍 Expected Behavior

simply to rename the button to "save backend" in case of an edit

### 📃 Additional Context

i hope i didnt opened to many issues ;)
i would like you to improve a software that i love to use daily

### 🏢 Code of Conduct Acknowledgement

- [X] I have read the [Contributing Guidelines](https://github.com/logicleai/logicle/blob/main/CONTRIBUTING.md)

**Comment by protoism** [comment]
Thanks!
