### ISSUE TITLE
[Feature]: Implement Environment Variable to Lock LLM Provider Configuration

### ISSUE THREAD

**Issue by enricobellato** [logicleai/logicle#3]
## Requirement
- Introduce a new environment variable named `LLM_PROVIDER_CONFIG_LOCK`.
- When `LLM_PROVIDER_CONFIG_LOCK` is set to `true`, the application should prohibit any attempts to add, edit, or modify LLM provider configurations.
- The lock should affect both UI and API functionalities related to LLM provider configuration.
- Appropriate error messages should be displayed to users attempting to modify the configuration while the lock is active.

**Comment by protoism** [comment]
No need for error messages client side: all buttons and edits and similar are disabled
