### ISSUE TITLE
[FEATURE] Prompt User Before Exiting Unsaved Assistant Editor

### ISSUE THREAD

**Issue by enricobellato** [logicleai/logicle#34]
### 🔖 Describe the Feature

Currently, when a user opens the assistant editor and closes it without saving, the system automatically saves the assistant, but it is completely empty (check the screenshot below).
![Screenshot 2024-03-18 alle 22 54 15](https://github.com/logicleai/logicle/assets/58302982/7c4534b1-5313-4264-9a52-9321ec6b9256)

This behavior can lead to the accumulation of empty, unused assistant instances within the application, cluttering the user's workspace and potentially causing confusion. The expected behavior is for the application to prompt the user if they attempt to exit the assistant builder without saving their work. This prompt should ask the user if they wish to exit without saving. If the user confirms, the application should automatically delete the unsaved assistant, ensuring that no empty assistant instances are left behind.

### 🎤 Justification for the Feature

This feature is needed to enhance the user experience by preventing the unintentional creation of empty assistant instances. It addresses the issue where users might accidentally close the editor, perhaps thinking they have saved their work or deciding not to proceed with the creation of a new assistant. By implementing a prompt that explicitly asks users if they wish to exit without saving, it ensures that users are making a conscious decision about their work. This not only helps in maintaining a cleaner, more organized workspace but also aids in avoiding the potential confusion that can arise from encountering unexpected empty assistants in their project list.

### ✌️ Proposed Solution

The proposed solution involves implementing a confirmation dialog that triggers when a user attempts to close the assistant editor without saving their work. This dialog should clearly communicate the consequences of exiting without saving, offering options to either proceed with exiting (and thus deleting the unsaved assistant) or cancel the action to return to the editor and save their work. Implementing this feature requires changes to the editor's close event handling to check for unsaved changes and conditionally present the confirmation dialog based on this check.

### 👀 Duplicate Check

- [X] I have searched and found no similar feature request

### 🏢 Code of Conduct Acknowledgement

- [X] I have read the [Contributing Guidelines](https://github.com/logicleai/logicle/blob/main/CONTRIBUTING.md)

**Comment by protoism** [comment]
It makes sense, but... this is exactly OpenAI's behaviour.

**Comment by protoism** [comment]
The shard proposal is adding a "state" to an assistant.

"draft": the assistant is in creation, it is not eligible for new chats (i.e. not visible in explore)
"active": the assistant is ready to be used
"deleted": the assistant is still there, it is even visible if a chat using it is opened, but no new messages can be posted

In general, deleting from db entities with lots of foreign keys is just looking for trouble...:

In the case of assistants:
* chats, we probably don't want to delete them... 
* uploaded files, we might want to defer deletion to a later time
...
...

But there are probably a few other cases in which the same reasoning applies

**Comment by protoism** [comment]
Preliminary work has been done on this. Quite rough... it always alerts even if there are no modifications pending.
My feeling is that this is not the right solution, and constantly saving drafts is the way to go, as in https://github.com/logicleai/logicle/issues/61

**Comment by protoism** [comment]
Closing this issue, as it is less elegant, less future proof, than assistant draft mode
