### ISSUE TITLE
[BUG] Misleading Error Message for Incorrect Login Credentials

### ISSUE THREAD

**Issue by enricobellato** [logicleai/logicle#42]
### 📜 Issue Description

When attempting to log in with incorrect credentials on the login page (auth/login), the error message displayed in the UI is "Configuration" instead of a message indicating incorrect credentials. Upon inspecting the network activity, it's observed that the frontend makes a POST request to `https://<FQDN>/api/auth/callback/credentials`, and the backend responds with a 200 status code but returns the following JSON response: `{"url":"https://<FQDN>/api/auth/auth/login?error=Configuration"}`. This error message is misleading and should be updated to clearly indicate that the login attempt failed due to incorrect credentials, enhancing user experience significantly.

### 👟 Steps to Reproduce

1. Navigate to the login page at `auth/login`.
2. Attempt to log in with incorrect credentials.
3. Observe the error message displayed in the UI, which reads "Configuration".
4. Inspect the network activity to see the POST request to `https://<FQDN>/api/auth/callback/credentials` and the backend's JSON response.

### 👎 Current Behavior with Screenshots

Upon entering incorrect credentials, the UI displays an error message "Configuration", which is vague and misleading. This behavior can be observed directly on the login page and through the network activity, where the backend's response does not accurately reflect the error due to incorrect credentials.

<img width="505" alt="Screenshot 2024-03-25 alle 00 14 01" src="https://github.com/logicleai/logicle/assets/58302982/41c088f8-4a11-47fc-9adb-369b6cc19530">

### 👍 Expected Behavior

The expected behavior is for the UI to display a clear and specific error message indicating that the login attempt failed due to incorrect credentials. This would provide immediate, understandable feedback to the user, improving the overall user experience.

### 🏢 Code of Conduct Acknowledgement

- [X] I have read the [Contributing Guidelines](https://github.com/logicleai/logicle/blob/main/CONTRIBUTING.md)

**Comment by protoism** [comment]
The message is straight from nextauth. 
I'm not even sure we can fix it....

**Comment by protoism** [comment]
As incredible as it may seems, support has *just* been added. 

https://github.com/nextauthjs/next-auth/pull/9871
