### ISSUE TITLE
[FEATURE] Introduce SSO_CONFIG_LOCK Environment Variable

### ISSUE THREAD

**Issue by enricobellato** [logicleai/logicle#47]
### 🔖 Describe the Feature

Introduce a new environment variable named `SSO_CONFIG_LOCK`. When this variable is set to `true`, the application should prohibit any attempts to add, edit, or modify Single Sign-On (SSO) connections. This lock should affect functionalities across both the User Interface (specifically the `/admin/sso` page) and the API endpoints related to SSO connection configuration. Additionally, users attempting to modify the SSO configuration while the lock is active should be presented with appropriate error messages.

### 🎤 Justification for the Feature

The primary motivation for this feature is to allow installers to prevent administrators from changing SSO providers. This is crucial in scenarios where maintaining a consistent SSO provider setup is necessary to avoid administrative errors or unauthorized changes.

### ✌️ Proposed Solution

Implement an environment variable `SSO_CONFIG_LOCK`. When set to `true`, it should effectively disable any UI or API operations that would alter SSO configurations. This includes adding new SSO connections, editing existing ones, or removing them. The application should check the status of this environment variable before executing any such operations and, if the lock is active, return an error message to the user indicating that SSO configuration modifications are currently prohibited.

### 👀 Duplicate Check

- [X] I have searched and found no similar feature request

### 🏢 Code of Conduct Acknowledgement

- [X] I have read the [Contributing Guidelines](https://github.com/logicleai/logicle/blob/main/CONTRIBUTING.md)

**Comment by protoism** [comment]
Fixed in #51

**Comment by protoism** [comment]
Note: SSO_CONFIG_LOCK should be '1', not 'true', for consistency with other environment variables such as BOXYHQ_NO_ANALYTICS, DO_NOT_TRACK, ...
