### ISSUE TITLE
[FEATURE] Dynamic RAG Mode Activation and External Connection

### ISSUE THREAD

**Issue by enricobellato** [logicleai/logicle#59]
### 🔖 Describe the Feature

Introduce a variable for the dynamic enablement of experimental RAG mode and for connecting the database to external RAG servers, with a default value of 'false'.

### 🎤 Justification for the Feature

This feature provides flexibility for testing advanced functionalities and leveraging external resources without compromising system stability, as it defaults to 'false'.

### ✌️ Proposed Solution

Implement a configurable variable, 'ENABLE_EXPERIMENTAL_RAG_MODE', that when set to 'true', activates RAG mode and external database connections, ensuring it defaults to 'false'.

### 👀 Duplicate Check

- [X] I have searched and found no similar feature request

### 🏢 Code of Conduct Acknowledgement

- [X] I have read the [Contributing Guidelines](https://github.com/logicleai/logicle/blob/main/CONTRIBUTING.md)

**Comment by protoism** [comment]
ENABLE_ADVANCED_TOOLS is sort of doing what you ask.
But it's not (yet) an environment variable,
Is this ticket just about making this flag an environment variable?
Anyway the name  ENABLE_EXPERIMENTAL_RAG_MODE is a bit unfortunate, as tools are a bit more generic than RAG, and RAG is based on tools
