### ISSUE TITLE
[FEATURE] Refactor Select Assistant Page for Enhanced UI and UX

### ISSUE THREAD

**Issue by enricobellato** [logicleai/logicle#84]
### 🔖 Describe the Feature

The proposed feature involves a comprehensive refactor of the select assistant page. The key change is the removal of the second "chat" bar and the expansion of the UI to full screen. This adjustment will facilitate the introduction of a three-column layout, featuring cards for each assistant. Additionally, due to the removal of the workspace selector, it is proposed that each card includes a new piece of information indicating the sharing options of the assistant. This will be represented by a label positioned under the existing description label, detailing the sharing status (e.g., "Private" for personal assistants, "Shared with workspace X" for workspace-shared assistants, and "Everyone in the company" for company-wide shared assistants). This redesign aims to simplify the user experience and optimize the use of space within the application.

### 🎤 Justification for the Feature

This redesign is necessitated by the need to simplify the user experience (UX) and improve the spatial utilization within the application.

### ✌️ Proposed Solution

The proposed solution entails a two-fold approach. First, eliminate the second "chat" bar and expand the UI to a full-screen view. This will create space for a three-column layout. Second, introduce assistant cards within this layout, each card displaying essential information including a new label for sharing options (necessary after introduction of #83 ). This label will indicate whether the assistant is private, shared with a specific workspace, or available to everyone in the company. By implementing these changes, the select assistant page will offer a more intuitive and space-efficient user interface.
![IMG_3269](https://github.com/logicleai/logicle/assets/58302982/29452531-192a-4123-a6f2-2a6f0444b545)

### 👀 Duplicate Check

- [X] I have searched and found no similar feature request

### 🏢 Code of Conduct Acknowledgement

- [X] I have read the [Contributing Guidelines](https://github.com/logicleai/logicle/blob/main/CONTRIBUTING.md)

**Comment by protoism** [comment]
Where is the "create new assistant" button?
